version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
  api:
    ports:
    - "8080:8080"
    image: mytest
    environment:
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_URL: jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - postgres
