version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  rabbitmq:
    image: rabbitmq:management
  api:
    ports:
     - "8081:8080"
    image: patrikb/udacity-capstone-api
    environment:
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_URL: jdbc:postgresql://postgres:5432/postgres
      spring.rabbitmq.host: rabbitmq
      logging.level.org.springframework: TRACE
      logging.level.org.springframework.amqp: INFO
    depends_on:
      - postgres
      - rabbitmq
  frontend:
    image: patrikb/udacity-capstone-frontend
  reverseproxy:
    image: patrikb/udacity-capstone-reverseproxy
    ports: 
     - 8080:8080
     - 4200:8080
    depends_on:
     - api
     - frontend
