apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  type: NodePort
  externalName: client
  ports:
    - protocol: TCP
      port: 80
#     targetPort: 8080
  selector:
   app: client
