apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  externalName: frontend
  ports:
    - protocol: TCP
      port: 80
#     targetPort: 8080
  selector:
   app: frontend

