name: Client CI

on:
  push:
    paths:
    - 'client/**'
    - '.github/workflows/**'
    - 'k8-yaml/client*.yaml'

jobs:
  client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test and build Angular client
      working-directory: ./client
      run: |
        npm install
        npm run ci-test
        npm run build-prod
#    - run: npm test
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        path: ./client
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: patrikb/udacity-capstone-client
        tag_with_ref: true
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    - name: Trigger deploy
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f k8-yaml/client-deployment.yaml
    - name: Trigger rollout restart
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: rollout restart deployment/client
